version: '3.8'

services:
  frontend:
    build:
      context: .
      dockerfile: Dockerfile
    restart: unless-stopped
    ports:
      - "3000:3000"
    environment:
      - NODE_ENV=production
    env_file:
      - .env.production
    networks:
      - digimedic-network

  backend:
    build:
      context: ./backend
      target: production
    container_name: digimedic-backend-prod
    ports:
      - "8000:8000"
    environment:
      - PYTHONUNBUFFERED=1
    env_file:
      - .env.production
    restart: unless-stopped
    networks:
      - digimedic-network

networks:
  digimedic-network:
    driver: bridge 